name: Deploy

on:
  push:
    branches:
      - master
  # workflow_dispatch:
  #   inputs:
  #     crawler_run:
  #       required: false
  #       type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      # - name: Sync
      #   run: yarn sync:vitepress

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          # cname: example.com # if wanna deploy to custom domain
  # algolia:
  #     if: ${{ inputs.crawler_run }}
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v3
  #       - name: Get the content of algolia.json as config
  #         id: algolia_config
  #         run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
  #       - name: Push indices to Algolia
  #         uses: signcl/docsearch-scraper-action@master
  #         env:
  #           APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
  #           API_KEY: ${{ secrets.API_KEY }}
  #           CONFIG: ${{ steps.algolia_config.outputs.config }}